hydra:
  job:
    chdir: false

defaults:
  - hand: allegro_right
  - _self_

env:
  _target_: environments.pretty_env_cfg.NineLinkedRingsEnvCfg

device:
  _target_: teleoperation.geort_device.ManusViveGeortDevice
  cfg:
    _target_: teleoperation.geort_device.ManusViveGeortDeviceCfg
    xr_cfg:
      _target_: isaaclab.devices.openxr.XrCfg
  retargeters:
    - _target_: teleoperation.retargeters.wrist_retargeter.WristRetargeter
      cfg:
        _target_: teleoperation.retargeters.wrist_retargeter.WristRetargeterCfg
        hand_side: ${hand.side}
        sim_device: cpu
    - ${hand.retargeter}
