hydra:
  job:
    chdir: false

env:
  _target_: environments.gripper_env_cfg.NineLinkedRingsEnvCfg

robot_cfg:
  _target_: assets.assemblies_cfg.get_franka_hand_cfg

xr_cfg:
  _target_: isaaclab.devices.openxr.XrCfg
  anchor_pos: [0.0, 0.3, -0.7]
  anchor_rot: [0.59482, 0.0, 0.0, -0.80386]
  near_plane: 0.1

haply_device_cfg:
  _target_: isaaclab.devices.haply.se3_haply.HaplyDeviceCfg
  websocket_uri: "ws://localhost:10001"
  pos_sensitivity: 3.0
  data_rate: 200.0
  limit_force: 2.0